version: 0.2
phases:
    install:
        commands:
            - yarn install
    build:
        commands:
            - npm run generate
artifacts:
    files:
        - '**/*'
    base-directory: 'dist'
